# Tutorial 1 exercises


In this tutorial we'll go over a few exercises related to the content of the first lecture and tutorial.  In particular, you will

1. Work with different data types and data structures
2. Implement conditional logic
3. Write your own functions
4. Use Numpy and Pandas to solve multidimensional problem


## Data types and data structures

1. Extract the character 'o' from the string "Python" using conventional and negative indexing

In [1]:
my_string = "Python"

print(my_string[4])

o


2. Replace the string "Python" in the nested list with the string "Jupyter" instead

In [5]:
my_list = [1, 2, [3, 4,'Jupyter']]

my_list[2][2]="Python"
print(my_list)

[1, 2, [3, 4, 'Python']]


3. Replace the string "Python" in the nested list with the string "Jupyter" instead

In [6]:
my_list = [1, 2, [3, 4, [5, 6, 'Jupyter']]]

my_list[2][2][2]="Python"
print(my_list)

[1, 2, [3, 4, [5, 6, 'Python']]]


4. Arrange the following list in ascending order

In [9]:
my_list = [5, 4, 7, 2, 6, 1, 3,]

my_list.sort()
my_list

[1, 2, 3, 4, 5, 6, 7]

5. Extract the unique items from this list

In [11]:
my_list = [2,3,4,5,2,3,1,9,9,8,4,3,4,5,1]
my_list_set=set(my_list)
print(my_list_set)

{1, 2, 3, 4, 5, 8, 9}


6. Think of your own example for where a dictionary would be useful

In [ ]:
#Answer

7. Get "Python" from the following dictionary

In [13]:
my_dict = {'key1':'Python'}

print(my_dict['key1'])

Python


8. Get "Python" from the following dictionary

In [14]:
my_dict = {'key1':{'key2':'Python'}}

print(my_dict['key1']['key2'])

Python


9. Get "Python" from the following dictionary

In [15]:
my_dict = {'key1':[1,2,{'key2':['Jupyter',{'Anaconda':[3,4,['Python']]}]}]}

print(my_dict['key1'][2]['key2'][1]['Anaconda'][2])

['Python']


## Conditonal logic

10. Print the integers from 1 to 50. For every multiple of three, print "Snap", for every multiple of five, print "Crackle", and for numbers which are multiples of both three and five print "Pop".

In [ ]:
#Answer

11. Go through the sentence, <code>my_sentence</code>, and print every word of which the length of that word is an odd number

In [ ]:
my_sentence = "This is the sentence I would like you to print out and use for question 11 in this tutorial"

#Answer

## Functions

12. Write a function called <code>talk</code> that prints "Hello" every time it is called

In [51]:
def talk():
    print("Hello")
talk()

Hello


13. Write a function called <code>introduction</code> that takes a name as an input and prints the following
    "Hello, my name is [insert name here]"

In [52]:
def introduction(name):
    print("Hello "+name)
introduction("Kusi")    

Hello Kusi


14) Write a function that (i) takes two integers as input (ii) checks that the two inputs provided are indeed integers (prints out a message if not) (iii) returns the larger of the two integer and (iv) returns a string "equal" if the two numbers are equal

In [59]:
def func(int_1, int_2):
    if (type(int_1) != int) or (type(int_2) != int):
        print("one or both inputs are not integers")
    elif (int_1>int_2):
        return(int_1)
    elif (int_2>int_1):
        return(int_2)
    else: return("inputs given are equal") 

func("kusi",1)    

one or both inputs are not integers


15. Write a function that takes a word and capitalizes the first and third character

In [64]:
def capital(word):
    word = word[0].upper() + word[1] + word[2].upper()+word[3:]
    return(word)

capital("john")

'JoHn'

16. Write a function that takes three integers as inputs and checks whether the first integer is in the range between the second and third integer. If the second integer is greater than or equal to the third integer, print an appropriate message

In [67]:
def check_range(user_num, low_num, high_num):
    if user_num not in range(low_num, high_num):
        print("User_num not in the provided range")
    pass

check_range(10,1,8)

User_num not in the provided range


17. Write a function called "Blackjack" that takes 3 integers as an input. (i) If the sum is less than or equal to 21, return the sum. (ii) If the sum is greater than 21, but there is an 11 as one of the three integers, reduce the sum by 10 and then return the sum (iii) If the sum is greater than 21 - even after (ii) - return the string "Bust"

In [65]:
def Blackjack(int_1, int_2, int_3):
    sum_num=sum(int_1, int_2, int_3)
    if sum_num<21:
        return(sum_num)
    elif (sum_num>21) and (int_1==11 or int_2==11 or int_3==11):
        return(sum_num-10)
    elif (sum_num>21):
        return("Bust")
    

## Numpy and Pandas

17. The list <code>heights</code> contains a collection of heights expressed in inches. Convert these to metres which are simply, inches multipled by 0.0254

In [18]:
heights = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 
           76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74]

import numpy as np
heights_np=np.array(heights)*0.0254


array([ 1.8796,  1.8796,  1.8288,  1.8288,  1.8542,  1.7526,  1.7526,
        1.8034,  1.9304,  1.8034,  1.8542,  1.8542,  1.8796,  1.8796,
        1.7526,  1.778 ,  1.8542,  1.905 ,  1.9812,  2.0066,  1.9304,
        1.8796,  1.9304,  1.8288,  1.8034,  1.905 ,  1.9558,  1.8796,
        1.8542,  1.8796,  1.9812,  1.8542,  1.905 ,  1.8542,  1.905 ,
        1.905 ,  1.8796,  1.7526,  1.8034,  1.8796])

18. Using the same data, print out all the heights below 1.78m

In [22]:
b=heights_np<1.78
heights_np_below=heights_np[b]
print(heights_np_below)

array([ 1.7526,  1.7526,  1.7526,  1.778 ,  1.7526])

19. Convert the list to a 2D Numpy array

In [28]:
my_list = [[200, 74.4],
            [175, 100.6],
            [168, 92.2],
            [190, 80.2]]

my_list_np = np.array(my_list)
print(my_list_np)
my_list_np.ndim

[[ 200.    74.4]
 [ 175.   100.6]
 [ 168.    92.2]
 [ 190.    80.2]]


2

20. Convert the lists to a dictionary, and then to a data frame

In [79]:
names = ['United States', 'Australia', 'Russia', 'South Africa', 'Canada', 'Namibia']
north_hemis =  [True, False, True, False, True, False]
pop = [325.7, 24.1, 144.3, 55.9, 36.3, 2.5]

Country_keys=dict(zip(names, zip(north_hemis, pop)))

import pandas as pd
names_pd=pd.DataFrame(Country_keys)
names_pd

United States Australia Russia South Africa Canada Namibia
0          True     False   True        False   True   False
1         325.7      24.1  144.3         55.9   36.3     2.5

21. Import the following dataset as a pandas dataframe directly from the web and print out some summary statistics: http://tutorials.iq.harvard.edu/R/Rgraphics/dataSets/landdata-states.csv

In [50]:
FNAME = "http://tutorials.iq.harvard.edu/R/Rgraphics/dataSets/landdata-states.csv"
df = pd.read_csv(FNAME)
df.head()

State region     Date  Home.Value  Structure.Cost  Land.Value  \
0    AK   West  2010.25      224952          160599       64352   
1    AK   West  2010.50      225511          160252       65259   
2    AK   West  2009.75      225820          163791       62029   
3    AK   West  2010.00      224994          161787       63207   
4    AK   West  2008.00      234590          155400       79190   

   Land.Share..Pct.  Home.Price.Index  Land.Price.Index  Year  Qrtr  
0              28.6             1.481             1.552  2010     1  
1              28.9             1.484             1.576  2010     2  
2              27.5             1.486             1.494  2009     3  
3              28.1             1.481             1.524  2009     4  
4              33.8             1.544             1.885  2007     4